In [1]:
import plotly.io as pio
from umaplotly import uma_template

pio.templates.default = uma_template

In [2]:
import pandas as pd
import plotly.graph_objects as go

In [5]:
df = pd.read_csv(r'..\source\Plotly-Dashboards-with-Dash\Data\mpg.csv')
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [12]:
data = [go.Histogram(x=df.mpg, xbins=dict(start=0, end=50, size=2))]
layout = go.Layout(title="histogram")
go.Figure(data, layout)