In [2]:
#######
# Objective: Using the "flights" dataset available
# from the data folder as flights.csv
# create a heatmap with the following parameters:
# x-axis="year"
# y-axis="month"
# z-axis(color)="passengers"
######

# Perform imports here:

import plotly.io as pio
from umaplotly import uma_template
import pandas as pd
import plotly.graph_objects as go

pio.templates.default = uma_template

# Create a DataFrame from  "flights" data
df = pd.read_csv(r'..\source\Plotly-Dashboards-with-Dash\Data\flights.csv')
df

     year      month  passengers
0    1949    January         112
1    1949   February         118
2    1949      March         132
3    1949      April         129
4    1949        May         121
..    ...        ...         ...
139  1960     August         606
140  1960  September         508
141  1960    October         461
142  1960   November         390
143  1960   December         432

[144 rows x 3 columns]

In [8]:
# Define a data variable

data = [
    go.Heatmap(
        x=df.year,
        y=df.month,
        z=df.passengers,
        colorscale='jet'
    )
]

layout = go.Layout(title='flights')

# Create a fig from data and layout, and plot the fig
go.Figure(data, layout)